src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=9)
     */
    private $imdb_id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="smallint")
     */
    private $year_of_release;

    /**
     * @ORM\Column(type="smallint")
     */
    private $runtime;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $genre;

    /**
     * @ORM\Column(type="float")
     */
    private $imdb_rating;

    /**
     * @ORM\Column(type="simple_array")
     */
    private $directors = [];

    /**
     * @ORM\Column(type="simple_array")
     */
    private $top_actors = [];

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $my_rating;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $watched_on;

    /**
     * @ORM\Column(type="text")
     */
    private $discussion;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImdbId(): ?string
    {
        return $this->imdb_id;
    }

    public function setImdbId(string $imdb_id): self
    {
        $this->imdb_id = $imdb_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getRuntime(): ?int
    {
        return $this->runtime;
    }

    public function setRuntime(int $runtime): self
    {
        $this->runtime = $runtime;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getImdbRating(): ?float
    {
        return $this->imdb_rating;
    }

    public function setImdbRating(float $imdb_rating): self
    {
        $this->imdb_rating = $imdb_rating;

        return $this;
    }

    public function getYearOfRelease(): ?int
    {
        return $this->year_of_release;
    }

    public function setYearOfRelease(int $year_of_release): self
    {
        $this->year_of_release = $year_of_release;

        return $this;
    }

    public function getDirectors(): ?array
    {
        return $this->directors;
    }

    public function setDirectors(array $directors): self
    {
        $this->directors = $directors;

        return $this;
    }

    public function getTopActors(): ?array
    {
        return $this->top_actors;
    }

    public function setTopActors(array $top_actors): self
    {
        $this->top_actors = $top_actors;

        return $this;
    }

    public function getMyRating(): ?string
    {
        return $this->my_rating;
    }

    public function setMyRating(string $my_rating): self
    {
        $this->my_rating = $my_rating;

        return $this;
    }

    public function getWatchedOn(): ?string
    {
        return $this->watched_on;
    }

    public function setWatchedOn(string $watched_on): self
    {
        $this->watched_on = $watched_on;

        return $this;
    }

    public function getDiscussion(): ?string
    {
        return $this->discussion;
    }

    public function setDiscussion(?string $discussion): self
    {
        $this->discussion = $discussion;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Controller/MovieDataController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use App\Entity\Movie;
use App\Repository\MovieRepository;

class MovieDataController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(MovieRepository $repo): Response
    {
        return $this->render('movie_data/index.html.twig', [
            'movieData' => $repo->allData(),
        ]);
    }

    /**
     * @Route("/generate", name="generateStaticSite", methods={"GET"})
     */
    public function generateStaticSite(MovieRepository $repo): Response
    {
        $content = $this->renderView('movie_data/index.html.twig', [
            'movieData' => $repo->allData(),
        ]);

        $file = file_put_contents('../docs/index.html', $content);

        return $this->redirectToRoute('index');
    }
}

templates/base.html.twig
<!DOCTYPE html>

<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
    <meta name="Author" content="JagdCake" />
    <meta name="Keywords" content="HTML5, CSS3, No JavaScript, Tachyons CSS" />
    <meta name="Description" content="Data Website" />
    <!-- <meta http-equiv="Content-Security-Policy" content="script-src 'self'; style-src 'unsafe-inline' 'self'; connect-src 'self'; img-src 'self'; upgrade-insecure-requests"> -->
    <link rel="icon" type="image/png" href="images/favicon.png">
    {% block stylesheet %}
        <link rel="stylesheet" href="/css/tachyons.min.css"/>
    {% endblock %}
    <title>JC Data – {% block subtitle %}{% endblock %}</title>
    <style>
        .dropdown:hover .dropdown-content {
            display: block;
        }
    </style>
</head>
    <body>        
        <header class="tc pa2">
            <h1 class="f4 di mt0">View data from:</h1>
            <nav class="b di">
                <ul class="pa0 di">
                    <li class="di"><a href="{{ path('index') }}" class="color-inherit pa2 pb1 no-underline bb bw2">movies.jagdcake.com</a></li>
                </ul>
            </nav>
        </header>

        <details class="w-40-l w-80-m w-100 center f4 lh-copy mt2-ns mb0-ns mb3">
            <summary class="tc f2 pointer">What is this?</summary>
            <div class="ba-ns bt-0-ns bw1-ns ph2-ns ph3 pv1">
                <p class="mt0 mb3">A bunch of data, visualized using text, numbers and lists. At the moment, there is only one data source to choose from and that's my <a class="color-inherit" href="https://movies.jagdcake.com">“I watched a Movie!”</a> website.</p>
                <p class="mv3">All of the information is derived from movies I've watched / rewatched. Not very extensive but I believe a fair representation of my film-viewing habit.</p>
                <p class="mv3">The data is separated into cards based on a common theme. Basic numbers info, list cards — one-sentence overview followed by a top 10 (max) list.</p>
                <p class="mt3 mb0">For technical details, including data extraction and processing methods, visit the <a class="color-inherit" href="https://github.com/JagdCake/site.jc_data">GitHub repo</a>.</p>
            </div>
        </details>        
        {% block body %}{% endblock %}

        <footer class="pt2 pb4 tc">
            <address class="fs-normal">
                <h1 class="di f4 mt0">Contact:&nbsp;</h1>
                <span class="f4" id="email"><span>jc</span>@<span>jagdcake</span>.com</span>
            </address>

            <section class="pt2">
                <h1 class="di f4 mt0">Repository:&nbsp;</h1>
                <a class="f4 color-inherit" href="https://github.com/JagdCake/site.jc_data">GitHub</a>
            </section>
        </footer>
    </body>
</html>

templates/movie_data/_data.actors.html.twig
<article id="6" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
    <a href="#6" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <p>Looks like <em class="code pa1 bg-dark-purple light-gray b fs-normal">{{ movieData.topActors[0].principal }}</em> is popular.</p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">Number of movies starring:</h1>
        <ul>
            {% for actorData in movieData.topActors %}
                <li class="pa1 flex justify-between">
                    <span>{{ actorData.principal }}</span>
                    <span class="code b">{{ actorData.count }}</span>
                </li>
            {% endfor %}
        </ul>
   </section>
</article>

templates/movie_data/_data.decades.html.twig
{% set movieAgeAdjective = '_____' %}
{% if movieData.decades[0].decade >= 201 %}
    {% set movieAgeAdjective = 'newer' %}
{% elseif movieData.decades[0].decade >= 200 %}
    {% set movieAgeAdjective = 'new' %}
{% elseif movieData.decades[0].decade >= 198 %}
    {% set movieAgeAdjective = 'old' %}
{% else %}
    {% set movieAgeAdjective = 'older' %}
{% endif %}

<article id="4" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
    <a href="#4" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <p>I seem to prefer <em class="code pa1 bg-dark-purple light-gray b fs-normal">{{ movieAgeAdjective }}</em> movies; I've watched <strong class="code pa1 bg-dark-purple light-gray">{{ movieData.topYear[0].count }}</strong> from <time datetime="{{ movieData.topYear[0].year }}" class="code pa1 bg-dark-purple light-gray b">{{ movieData.topYear[0].year }}</time>.</p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">Number of movies per decade:</h1>
        <ul>
            {% for decadesData in movieData.decades %}
                <li class="pa1 flex justify-between">
                    <span>{{ decadesData.decade }}0s</span>
                    <span class="code b">{{ decadesData.count }}</span>
                </li>
            {% endfor %}
        </ul>
   </section>
</article>

templates/movie_data/_data.directors.html.twig
<article id="5" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
  <a href="#5" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <p><em class="code pa1 bg-dark-purple light-gray b fs-normal">{{ movieData.topDirectors[0].principal }}</em> stands out as a director.</p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">Number of movies directed by:</h1>
        <ul>
            {% for directorData in movieData.topDirectors %}
                <li class="pa1 flex justify-between">
                    <span>{{ directorData.principal }}</span>
                    <span class="code b">{{ directorData.count }}</span>
                </li>
            {% endfor %}
        </ul>
   </section>
</article>

templates/movie_data/_data.genres.html.twig
<article id="3" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
    <a href="#3" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <p>I mostly watch <em class="code pa1 bg-dark-purple light-gray b fs-normal">{{ movieData.topGenres[0].genre }}</em> movies, but I'm open to every genre.</p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">Number of movies per genre:</h1>
        <ul>
            {% for genreData in movieData.topGenres %}
                <li class="pa1 flex justify-between">
                    <span>{{ genreData.genre }}</span>
                    <span class="code b">{{ genreData.count }}</span>
                </li>
            {% endfor %}
        </ul>
   </section>
</article>

templates/movie_data/_data.imdb_ratings.html.twig
<article id="9" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
    <a href="#9" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <p>Compared to me, IMDb users give movies <em class="code pa1 bg-dark-purple light-gray b fs-normal">{{ movieData.ratingAdjective }}</em> ratings.</p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">Number of movies per IMDb rating (translated to my rating system):</h1>
        <ul>
            {% for ratingsData in movieData.imdbRatings %}
                <li class="pa1 flex justify-between">
                    <span>{{ ratingsData.rating }}</span>
                    <span class="code b">{{ ratingsData.count }}</span>
                </li>
            {% endfor %}
        </ul>
   </section>
</article>

templates/movie_data/_data.misc.html.twig
<article id="1" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
    <a href="#1" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <p>From <time datetime="2016-06" class="code pa1 bg-dark-purple light-gray b">June 2016</time> until <time datetime="{{ movieData.dateOfLastUpdate }}" class="code pa1 bg-dark-purple light-gray b">{{ movieData.dateOfLastUpdate | date('M d Y') }}</time>, I've watched <strong class="code pa1 bg-dark-purple light-gray">{{ movieData.totalNumberOfMovies }} movies</strong>.</p>
   </section>

    {% set difference = date(movieData.dateOfLastUpdate).diff(date('2016-06-01')) %}
    {% set percentOfTotalDays = ((movieData.totalTimeSpent.days / difference.days) * 100) | round(1) %}
    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <p>Out of <time datetime="{{ difference.days }}d" class="code pa1 bg-dark-purple light-gray b">{{ difference.days }}</time> days, I've spent <time datetime="{{ movieData.totalTimeSpent.days }}d" class="code pa1 bg-dark-purple light-gray b">{{ movieData.totalTimeSpent.days }}</time> watching films. That's <em class="code pa1 bg-dark-purple light-gray b fs-normal">{{ percentOfTotalDays }}%</em> of my time.</p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">More precisely:</h1>
        <p class="mt0"><time datetime="{{ movieData.totalTimeSpent.hours }}h {{ movieData.totalTimeSpent.remainingMinutes }}m" class="code pa1 bg-dark-purple light-gray b">{{ movieData.totalTimeSpent.hours }} hours and {{ movieData.totalTimeSpent.remainingMinutes }} minutes</time></p>
   </section>
</article>

templates/movie_data/_data.my_ratings.html.twig
<article id="8" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
    <a href="#8" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <p>I watch a lot of <em class="code pa1 bg-dark-purple light-gray b fs-normal">{{ movieData.myRatings[0].rating |
            replace({
                'Lettuce': 'Lettuces',
                'Savory': 'Savories',
                'Onion': 'Onions',
                'Tomato': 'Tomatoes',
                'Carrot': 'Carrots',
                'Eggplant': 'Eggplants',
            })
            }}</em>.</p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">Number of movies per my rating system:</h1>
        <ul>
            {% for ratingsData in movieData.myRatings %}
                <li class="pa1 flex justify-between">
                    <span>{{ ratingsData.rating }}</span>
                    <span class="code b">{{ ratingsData.count }}</span>
                </li>
            {% endfor %}
        </ul>
   </section>
</article>

templates/movie_data/_data.rating_system.html.twig
<article id="7" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
    <a href="#7" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <p>I have a <em class="code pa1 bg-dark-purple light-gray b fs-normal">food-inspired</em> rating system.</p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">My ratings compared to IMDb stars:</h1>
        <ul>
            <li class="pa1 flex justify-between">
                <span>Sublime Lettuce</span>
                <span class="code b">9–10</span>
            </li>
            <li class="pa1 flex justify-between">
                <span>Amazing Savory</span>
                <span class="code b">7.9–8.9</span>
            </li>
            <li class="pa1 flex justify-between">
                <span>Great Onion</span>
                <span class="code b">6–7.8</span>
            </li>
            <li class="pa1 flex justify-between">
                <span>Good Tomato</span>
                <span class="code b">5–5.9</span>
            </li>
            <li class="pa1 flex justify-between">
                <span>Decent Carrot</span>
                <span class="code b">4–4.9</span>
            </li>
            <li class="pa1 flex justify-between">
                <span>Bad Eggplant</span>
                <span class="code b">1–3.9</span>
            </li>
        </ul>
   </section>
</article>

templates/movie_data/_data.runtime.html.twig
<article id="2" class="bg-light-gray tl ph4 w-60-m w-25-l ma4-ns ba-ns bw1-ns self-start-ns">
    <a href="#2" class="db tc w1 h1 center"></a>
    <section class="pv2">
        <h1 class="f4 mb0">Longest movie:</h1>
        <p class="mt0"><time datetime="{{ movieData.longestMovie.hours }}h {{ movieData.longestMovie.minutes }}m" class="code pa1 bg-dark-purple light-gray b">{{ movieData.longestMovie.hours }} hours and {{ movieData.longestMovie.minutes }} minutes</time></p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">Shortest movie:</h1>
        <p class="mt0"><time datetime="{{ movieData.shortestMovie.hours }}h {{ movieData.shortestMovie.minutes }}m" class="code pa1 bg-dark-purple light-gray b">{{ movieData.shortestMovie.hours }} hour and {{ movieData.shortestMovie.minutes }} minutes</time></p>
   </section>

    <section class="pv2 bt bb-0 bl-0 br-0 bw1 b--dashed">
        <h1 class="f4 mb0">Average runtime:</h1>
        <p class="mt0"><time datetime="{{ movieData.averageRuntime.hours }}h {{ movieData.averageRuntime.minutes }}m" class="code pa1 bg-dark-purple light-gray b">{{ movieData.averageRuntime.hours }} hour and {{ movieData.averageRuntime.minutes }} minutes</time></p>
   </section>
</article>

templates/movie_data/index.html.twig
{% extends 'base.html.twig' %}

{% block subtitle %}Movies{% endblock %}

{% block body %}
    <div class="bg-white dark-purple sans-serif">
        <main class="f4 lh-copy tc flex-ns flex-wrap-ns justify-center-ns">

            {{ include('movie_data/_data.misc.html.twig') }}
            <div class="separator w-100 h2 dn-ns"></div>
            {{ include('movie_data/_data.runtime.html.twig') }}
            <div class="separator w-100 h2 dn-ns"></div>
            {{ include('movie_data/_data.genres.html.twig') }}

            <div class="separator w-100 h2 dn-ns"></div>
            {{ include('movie_data/_data.decades.html.twig') }}
            <div class="separator w-100 h2 dn-ns"></div>
            {{ include('movie_data/_data.directors.html.twig') }}
            <div class="separator w-100 h2 dn-ns"></div>
            {{ include('movie_data/_data.actors.html.twig') }}

            <div class="separator w-100 h2 dn-ns"></div>
            {{ include('movie_data/_data.rating_system.html.twig') }}
            <div class="separator w-100 h2 dn-ns"></div>
            {{ include('movie_data/_data.my_ratings.html.twig') }}
            <div class="separator w-100 h2 dn-ns"></div>
            {{ include('movie_data/_data.imdb_ratings.html.twig') }}

        </main>
    </div>
{% endblock %}